### ISSUE TITLE
How to serve a specific public folder depending on the sub domain vhost

### ISSUE THREAD

**Issue by KayHS** [expressjs/vhost#31] opened 2018-10-12 14:47 UTC
Hi,

Ive asked this question on stackoverflow and unfortunately no one has given me an answer.  So i hope you don't mind me asking here.

> I want to serve a public folder with the same name as the subdomain.

Depending on the vhost (*.localhost.com) i want to serve a specific public app. For example

`app1.localhost.com` would serve `/public/app1/index.html`

**etc/hosts** 

```
127.0.0.1   localhost
127.0.0.1   app1.localhost
```

**routes.js**
```
        this.app = express();
        this.config = new Config();

        this.static = connect();

        this.app.use(vhost("*.localhost", (req, res, next) => {
            const host = req.vhost[0];
            const hostPath = path.join(__dirname, "public", host);
            this.static.use(serveStatic(hostPath));
            next();
        }));

        this.app.use("/api/v1/core", CoreRouter);

```

This just . gives me 

> Cannot GET /

**Comment by dougwilson** [comment] 2018-10-12 14:49
Just open the issue once.

**Comment by dougwilson** [comment] 2018-10-12 14:49
Duplicate of https://github.com/expressjs/serve-static/issues/115

**Closed by dougwilson** 2018-10-12 14:49 UTC
